// Master list of all Adobe products
// This list is used to identify which products don't have associated labs

export const MASTER_PRODUCTS_LIST = [
  'Adobe Acrobat Sign',
  'Adobe Acrobat Studio',
  'Adobe Advertising',
  'Adobe Analytics',
  'Adobe Audience Manager',
  'Adobe Brand Concierge',
  'Adobe Campaign',
  'Adobe Commerce',
  'Adobe Commerce Optimizer',
  'Adobe Content Analytics',
  'Adobe Customer Journey Analytics',
  'Adobe Customer Journey Analytics B2B Edition',
  'Adobe Experience Manager Assets',
  'Adobe Experience Manager Forms',
  'Adobe Experience Manager Guides',
  'Adobe Experience Manager Sites',
  'Adobe Experience Manager Sites Optimizer',
  'Adobe Experience Platform',
  'Adobe Experience Platform Agent Orchestrator',
  'Adobe Express',
  'Adobe Firefly',
  'Adobe Firefly Creative Production',
  'Adobe Firefly Custom Models',
  'Adobe Firefly Design Intelligence',
  'Adobe Firefly Foundry',
  'Adobe Firefly Services',
  'Adobe Frame.io',
  'Adobe GenStudio',
  'Adobe GenStudio Content Marketing',
  'Adobe GenStudio for Connected TV',
  'Adobe GenStudio for Creative Production',
  'Adobe GenStudio for Performance Marketing',
  'Adobe Journey Optimizer',
  'Adobe Journey Optimizer B2B Edition',
  'Adobe Journey Optimizer Experimentation Accelerator',
  'Adobe Learning Manager',
  'Adobe LLM Optimizer',
  'Adobe Marketo Engage',
  'Adobe Marketing Agent for Microsoft 365 Copilot',
  'Adobe Marketo Measure',
  'Adobe Mix Modeler',
  'Adobe Primetime Pass',
  'Adobe Real-Time CDP',
  'Adobe Real-Time CDP B2B Edition',
  'Adobe Real-Time CDP Collaboration',
  'Adobe Target',
  'Adobe Workfront'
];
